# local: string, the root path of the local repository.
# remote: [string, ...], remote repository addresses, latest ranked first
# clean: bool, true if use "local/.gitignore" as pattern to clean up redundant files and directories.

# [[repos]]
# local = 'F:/C/C Programs'
# remote = [
#     'https://github.com/chen-qingyu/C-Programs.git',
#     'https://gitee.com/ChobitsY/c-programs.git',
# ]
# clean = true

[[repos]]
local = 'F:/Python/Python Programs'
remote = { github = 'https://github.com/chen-qingyu/Python-Programs.git', gitee = 'https://gitee.com/ChobitsY/python-programs.git' }
clean = false

# [[repos]]
# local = 'F:/Java/Java Programs'
# remote = [
#     'https://github.com/chen-qingyu/Java-Programs.git',
#     'https://gitee.com/ChobitsY/java-programs.git',
# ]
# clean = false

# [[repos]]
# local = 'F:/C/C Primer Plus'
# remote = [
#     'https://github.com/chen-qingyu/C-Primer-Plus.git',
#     'https://gitee.com/ChobitsY/c-primer-plus.git',
# ]
# clean = true

# [[repos]]
# local = 'F:/Java/StuScore'
# remote = [
#     'https://github.com/chen-qingyu/StuScore.git',
#     'https://gitee.com/ChobitsY/stu-score.git',
# ]
# clean = false

# [[repos]]
# local = 'F:/OSTEP'
# remote = [
#     'https://github.com/chen-qingyu/OSTEP.git',
#     'https://gitee.com/ChobitsY/ostep.git',
# ]
# clean = false

# [[repos]]
# local = 'F:/Projects/BadApple'
# remote = [
#     'https://github.com/chen-qingyu/Bad-Apple',
#     'https://gitee.com/ChobitsY/bad-apple',
# ]
# clean = true

[[repos]]
local = 'F:/Projects/HelloWorld'
remote = { github = 'https://github.com/chen-qingyu/Hello-World.git', gitee = 'https://gitee.com/ChobitsY/hello-world.git' }
clean = false

[[repos]]
local = 'F:/Projects/LinearAlgebra'
remote = { github = 'https://github.com/chen-qingyu/Linear-Algebra.git', gitee = 'https://gitee.com/ChobitsY/linear-algebra.git' }
clean = false

# [[repos]]
# local = 'F:/Projects/Love Miao'
# remote = ['github', 'gitee']
# clean = false

# [[repos]]
# local = 'F:/Racket/HtDP'
# remote = ['github', 'gitee']
# clean = false

# [[repos]]
# local = 'F:/STM32/STM32 Programs'
# remote = ['github', 'gitee']
# clean = true

# [[repos]]
# local = 'F:/TeX'
# remote = ['github', 'gitee']
# clean = true

# [[repos]]
# local = 'F:/Projects/TestTime'
# remote = ['github', 'gitee']
# clean = true

[[repos]]
local = 'F:/Projects/MDS'
remote = { github = 'https://github.com/chen-qingyu/MDS.git', gitee = 'https://gitee.com/ChobitsY/mds.git' }
clean = false

[[repos]]
local = 'F:/Projects/MDSPP'
remote = { github = 'https://github.com/chen-qingyu/MDSPP.git', gitee = 'https://gitee.com/ChobitsY/mdspp.git' }
clean = false

[[repos]]
local = 'F:/Projects/MyLinearAlgebra'
remote = { github = 'https://github.com/chen-qingyu/MyLinearAlgebra.git', gitee = 'https://gitee.com/ChobitsY/my-linear-algebra.git' }
clean = true
