# name: the repository name.
# abbr: the abbreviation of repository name, no spaces, case insensitive.
# local: the root path of the local repository.
# remote: remote repository addresses.
# upstream: the upstream remote repository host.
# clean: true if use ".gitignore" as pattern to clean up redundant files and directories recursively.

[[repos]]
name = 'HelloWorld'
abbr = 'HW'
local = 'F:/Projects/'
remote = { github = 'https://github.com/chen-qingyu/HelloWorld.git', gitee = 'https://gitee.com/ChobitsY/HelloWorld.git' }
upstream = 'github'
clean = false

[[repos]]
name = 'HelloDataStructure'
abbr = 'HDS'
local = 'F:/Projects/'
remote = { github = 'https://github.com/chen-qingyu/HelloDataStructure.git', gitee = 'https://gitee.com/ChobitsY/HelloDataStructure.git' }
upstream = 'github'
clean = false

[[repos]]
name = 'MyDataStructure'
abbr = 'MDS'
local = 'F:/Projects/'
remote = { github = 'https://github.com/chen-qingyu/MyDataStructure.git', gitee = 'https://gitee.com/ChobitsY/MyDataStructure.git' }
upstream = 'github'
clean = false

[[repos]]
name = 'MyLinearAlgebra'
abbr = 'MLA'
local = 'F:/Projects/'
remote = { github = 'https://github.com/chen-qingyu/MyLinearAlgebra.git', gitee = 'https://gitee.com/ChobitsY/MyLinearAlgebra.git' }
upstream = 'github'
clean = true

[[repos]]
name = 'BadApple'
abbr = 'BA'
local = 'F:/Projects/'
remote = { github = 'https://github.com/chen-qingyu/BadApple', gitee = 'https://gitee.com/ChobitsY/BadApple' }
upstream = 'github'
clean = true

[[repos]]
name = 'C Code'
abbr = 'CC'
local = 'F:/'
remote = { github = 'https://github.com/chen-qingyu/C-Code.git', gitee = 'https://gitee.com/ChobitsY/C-Code.git' }
upstream = 'github'
clean = true

[[repos]]
name = 'Python Code'
abbr = 'PC'
local = 'F:/'
remote = { github = 'https://github.com/chen-qingyu/Python-Code.git', gitee = 'https://gitee.com/ChobitsY/Python-Code.git' }
upstream = 'github'
clean = false

[[repos]]
name = 'STM32 Code'
abbr = 'SC'
local = 'F:/'
remote = { github = 'https://github.com/chen-qingyu/STM32-Code.git', gitee = 'https://gitee.com/ChobitsY/STM32-Code.git' }
upstream = 'github'
clean = true

[[repos]]
name = 'TeX Code'
abbr = 'TC'
local = 'F:/'
remote = { github = 'https://github.com/chen-qingyu/TeX-Code.git', gitee = 'https://gitee.com/ChobitsY/TeX-Code.git' }
upstream = 'github'
clean = true

[[repos]]
name = 'C Primer Plus'
abbr = 'CPP'
local = 'F:/Learn/'
remote = { github = 'https://github.com/chen-qingyu/C-Primer-Plus.git', gitee = 'https://gitee.com/ChobitsY/c-primer-plus.git' }
upstream = 'github'
clean = true

[[repos]]
name = 'OSTEP'
abbr = 'OSTEP'
local = 'F:/Learn/'
remote = { github = 'https://github.com/chen-qingyu/OSTEP.git', gitee = 'https://gitee.com/ChobitsY/ostep.git' }
upstream = 'github'
clean = false

[[repos]]
name = 'HtDP'
abbr = 'HTDP'
local = 'F:/Learn/'
remote = { github = 'https://github.com/chen-qingyu/HtDP.git', gitee = 'https://gitee.com/ChobitsY/htdp.git' }
upstream = 'github'
clean = false
